'''Workflow for the CAMP short-read quality control module.'''


from contextlib import redirect_stderr
import os
from os.path import basename, join
import pandas as pd
import shutil
from utils import Workflow_Dirs, ingest_samples, calc_read_lens, sample_statistics

from itertools import product

# Load and/or make the working directory structure
dirs = Workflow_Dirs(config['work_dir'], 'short_read_qc')


# Load sample names and input files 
SAMPLES = ingest_samples(config['samples'], dirs.TMP)


# Configure optional flags
dedup_flag = '--dedup' if config['dedup'] else '--dont_eval_duplication'


# --- Workflow output --- #

all_results = [join(dirs.OUT, 'final_reports', 'read_stats.csv'),
        join(dirs.OUT, 'final_reports', 'samples.csv')]
if config['qc_option']:
    all_results.extend([join(dirs.OUT, 'final_reports', 'pre_multiqc_report.html'), join(dirs.OUT, 'final_reports', 'post_multiqc_report.html')])
else:
    print("Here we are printing!")

print(all_results)


if not config['qc_option']:
    with open(join(dirs.OUT, '4_summary', 'pre_multiqc_report.html'), 'w') as fp:
        pass
    with open(join(dirs.OUT, '4_summary', 'post_multiqc_report.html'), 'w') as fp:
        pass

rule all:
    input:
        # expand(join(dirs.OUT, 'final_reports', '{eval}_multiqc_report.html'), eval = ['pre', 'post']),
        # join(dirs.OUT, 'final_reports', 'read_stats.csv'),
        # join(dirs.OUT, 'final_reports', 'samples.csv')
        all_results


def workflow_mode(wildcards):
    if config['use_host_filter']:
        return [ join(dirs.OUT, '2_host_removal', '{sample}_1.fastq.gz'),
                 join(dirs.OUT, '2_host_removal', '{sample}_2.fastq.gz') ]
    else:
        return [ join(dirs.OUT, '1_adapter_removal', '{sample}_1.fastq.gz'),
                 join(dirs.OUT, '1_adapter_removal', '{sample}_2.fastq.gz') ]


# --- Workflow modules --- #


# Multi-purpose filter: Quality, length, Ns, polyG/X
# No deduplication to keep relative abundance signal
rule filter_low_qual:
    input:
        fwd = join(dirs.TMP,'{sample}_1.fastq.gz'),
        rev = join(dirs.TMP,'{sample}_2.fastq.gz'),
    output:
        fwd = join(dirs.OUT, '0_lowqual_removal', '{sample}_1.fastq.gz'),
        rev = join(dirs.OUT, '0_lowqual_removal', '{sample}_2.fastq.gz'),
    log:
        join(dirs.LOG, 'lowqual_removal', '{sample}.out'),
    threads: config['filter_lowqual_threads'],
    resources:
        mem_mb = config['filter_lowqual_mem_mb'],
    params:
        minqual = config['minqual'],
        dedup = dedup_flag,
        sample = '{sample}',
        out_dir = join(dirs.OUT, '0_lowqual_removal'),
    shell:
        """
        fastp -i {input.fwd} -I {input.rev} -o {output.fwd} -O {output.rev} \
            -q {params.minqual} {params.dedup} --thread {threads} \
            -j {params.out_dir}/{params.sample}.json \
            -h {params.out_dir}/{params.sample}.html > {log} 2>&1
        """

# fastp -i 306557045_S155_L003_R1_001.fastq.gz -I 306557045_S155_L003_R2_001.fastq.gz -o low_qual_306557045_S155_L003_R1_001.fastq.gz -O low_qual_306557045_S155_L003_R2_001.fastq.gz -q 30 False --thread 24 
# /usr/bin/time -v fastp -i 306555939_S142_L003_R1_001.fastq.gz -I 306555939_S142_L003_R2_001.fastq.gz -o low_qual_306555939_S142_L003_R1_001.fastq.gz -O low_qual_306555939_S142_L003_R2_001.fastq.gz -q 30 False --thread 16
rule filter_adapters:
    input:
        fwd = join(dirs.OUT, '0_lowqual_removal', '{sample}_1.fastq.gz'),
        rev = join(dirs.OUT, '0_lowqual_removal', '{sample}_2.fastq.gz'),
    output:
        fwd  = join(dirs.OUT, '1_adapter_removal', '{sample}_1.fastq.gz'),
        rev  = join(dirs.OUT, '1_adapter_removal', '{sample}_2.fastq.gz'),
    threads: config['filter_adapters_threads'],
    params:
        outbase = join(dirs.OUT, '1_adapter_removal', '{sample}'),
    shell:
        """
        AdapterRemoval --threads {threads} --file1 {input.fwd} --file2 {input.rev} \
        --output1 {output.fwd} --output2 {output.rev} --trimns --trimqualities --gzip
        """

# /usr/bin/time -v java -classpath /home/lam4003/bin/anaconda3/share/trimmomatic-0.39-2/trimmomatic.jar org.usadellab.trimmomatic.TrimmomaticPE -phred33 -threads 2 /athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/low_qual_306555939_S142_L003_R1_001.fastq.gz /athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/low_qual_306555939_S142_L003_R2_001.fastq.gz /athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/adaptor_removal_306555939_S142_L003_R1_001.fastq.gz /athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/adaptor_removal_306555939_S142_L003_R2_001.fastq.gz /athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/adaptor_removal_306555939_S142_L003_R1_001_unp.fastq.gz /athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/adaptor_removal_306555939_S142_L003_R2_001_unp.fastq.gz ILLUMINACLIP:/home/lam4003/bin/anaconda3/share/trimmomatic-0.39-2/adapters/TruSeq3-PE-2.fa:2:30:10:3:true

# /usr/bin/time -v java -classpath /home/lam4003/bin/anaconda3/share/trimmomatic-0.39-2/trimmomatic.jar org.usadellab.trimmomatic.TrimmomaticPE -phred33 -threads 12 /athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/low_qual_306557045_S155_L003_R1_001.fastq.gz /athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/low_qual_306557045_S155_L003_R2_001.fastq.gz /athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/adaptor_removal_306557045_S155_L003_R1_001.fastq.gz /athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/adaptor_removal_306557045_S155_L003_R2_001.fastq.gz /athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/adaptor_removal_306557045_S155_L003_R1_001_unp.fastq.gz /athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/adaptor_removal_306557045_S155_L003_R1_001_unp.fastq.gz ILLUMINACLIP:/home/lam4003/bin/anaconda3/share/trimmomatic-0.39-2/adapters/TruSeq3-PE-2.fa:2:30:10:3:true

# # cutadapt
# /usr/bin/time -v cutadapt -a ADAPTER_FWD -A ADAPTER_REV --cores=16 -o /athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/cutadapt_306557045_S155_L003_R1_001.fastq.gz -p /athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/cutadapt_306557045_S155_L003_R2_001.fastq.gz /athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/low_qual_306557045_S155_L003_R1_001.fastq.gz /athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/low_qual_306557045_S155_L003_R2_001.fastq.gz

# # AdapterRemoval
# /usr/bin/time -v AdapterRemoval --threads 16 --file1 /athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/low_qual_306557045_S155_L003_R1_001.fastq.gz --file2 /athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/low_qual_306557045_S155_L003_R2_001.fastq.gz --basename /athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/AAAdapterRemoval_306557045_S155_L003_RX_001 --trimns --trimqualities --collapse  --gzip
# /usr/bin/time -v AdapterRemoval --threads 16 --file1 /athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/low_qual_306557045_S155_L003_R1_001.fastq.gz --file2 /athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/low_qual_306557045_S155_L003_R2_001.fastq.gz --output1 /athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/AAAdapterRemoval_306557045_S155_L003_R1_001.fastq.gz --output2 /athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/AAAdapterRemoval_306557045_S155_L003_R2_001.fastq.gz --trimns --trimqualities --gzip
rule filter_host_reads:
    input:
        fwd = join(dirs.OUT, '1_adapter_removal', '{sample}_1.fastq.gz'),
        rev = join(dirs.OUT, '1_adapter_removal', '{sample}_2.fastq.gz')
    output:
        fwd = join(dirs.OUT, '2_host_removal', '{sample}_1.fastq.gz'),
        rev = join(dirs.OUT, '2_host_removal', '{sample}_2.fastq.gz')
    log:
        join(dirs.LOG, 'host_removal', '{sample}.out'),
    threads: config['filter_host_reads_threads'],
    resources:
        mem_mb = config['filter_host_reads_mem_mb'],
    params:
        prefix = join(dirs.OUT, '2_host_removal', '{sample}'),
        host_ref_db = config['host_reference_database'],
    run:
        if config['use_host_filter']:
            shell("bowtie2 --very-sensitive --threads {threads} -x {params.host_ref_db} -1 {input.fwd} -2 {input.rev} --un-conc-gz {params.prefix}_%.fastq.gz > {params.prefix}.sam 2> {log} rm {params.prefix}.sam")
        else:
            shell("touch {output.fwd} && touch {output.rev}")
            print("empty host cleaning files created: {output.fwd} & {output.rev}")



rule filter_seq_errors:
    input:
        workflow_mode,
    output:
        fwd = join(dirs.OUT, '3_error_removal', '{sample}', 'corrected', '{sample}_1.fastq.00.0_0.cor.fastq.gz'),
        rev = join(dirs.OUT, '3_error_removal', '{sample}', 'corrected', '{sample}_2.fastq.00.0_0.cor.fastq.gz'),
    log:
        join(dirs.LOG, 'error_removal', '{sample}.out')
    threads: config['filter_seq_errors_threads'],
    resources:
        mem_mb = config['filter_seq_errors_mem_mb'],
    params:
        prefix = join(dirs.OUT, '3_error_removal', '{sample}', 'corrected', '{sample}'),
        out_dir = join(dirs.OUT, '3_error_removal', '{sample}', ),
        fwd_repair = join(dirs.OUT, '3_error_removal', '{sample}_repaired_1.fastq.00.0_0.cor.fastq.gz'),
        rev_repair = join(dirs.OUT, '3_error_removal', '{sample}_repaired_2.fastq.00.0_0.cor.fastq.gz'),
        fwd_tadpole = join(dirs.OUT, '3_error_removal', '{sample}_1.fastq.00.0_0.cor.fastq.gz'),
        rev_tadpole = join(dirs.OUT, '3_error_removal', '{sample}_2.fastq.00.0_0.cor.fastq.gz'),
    run:
        if config['error_correct_option'] == 'spades':
            shell("spades.py --only-error-correction --meta -t {threads} -m {resources.mem_mb} -1 {input[0]} -2 {input[1]} -o {params.out_dir} > {log} 2>&1")
        elif config['error_correct_option'] == 'tadpole':
        # to add repair
            shell("/home/chf4012/camp_short-read-quality-control/configs/tadpole/bbmap/repair.sh in={input[0]} in2={input[1]} out={params.fwd_repair} out2={params.rev_repair} && /home/chf4012/camp_short-read-quality-control/configs/tadpole/bbmap/tadpole.sh mode=correct  t={threads} in={params.fwd_repair} in2={params.rev_repair} out={output.fwd} out2={output.rev}")
            # shell("/home/chf4012/camp_short-read-quality-control/configs/tadpole/bbmap/tadpole.sh mode=correct  t={threads} in={input[0]} in2={input[1]} out={params.fwd_tadpole} out2={params.rev_tadpole}")
            # shell("/configs/tadpole/bbmap/tadpole.sh mode=correct  t={threads} in={input[0]} in2={input[1]} out={param.fwd_tadpole} out2={param.rev_tadpole} > {log} 2>&1")
            print("tadpole run on", '{sample}_1.fastq.00.0_0.cor.fastq.gz')



# || /configs/tadpole/bbmap/repair.sh in={input[0]} in2={input[1]} out={params.fwd_repair} out2={params.rev_repair} && /home/chf4012/camp_short-read-quality-control/configs/tadpole/bbmap/tadpole.sh mode=correct  t={threads} in={params.fwd_repair} in2={params.rev_repair} out={params.fwd_tadpole} out2={params.rev_tadpole} > {log} 2>&1
# /usr/bin/time -v /home/chf4012/camp_short-read-quality-control/configs/tadpole/bbmap/repair.sh  t=16 in=/athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/adaptor_removal_306555939_S142_L003_R1_001.fastq.gz in2=/athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/adaptor_removal_306555939_S142_L003_R2_001.fastq.gz out=/athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/repaired_306555939_S142_L003_R1_001.fastq.gz out2=/athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/repaired_306555939_S142_L003_R2_001.fastq.gz
# /usr/bin/time -v /home/chf4012/camp_short-read-quality-control/configs/tadpole/bbmap/tadpole.sh mode=correct  t=16 in=/athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/repaired_306555939_S142_L003_R1_001.fastq.gz in2=/athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/repaired_306555939_S142_L003_R1_001.fastq.gz out=/athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/seq_error_306555939_S142_L003_R1_001.fastq.gz out2=/athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/seq_error_306555939_S142_L003_R2_001.fastq.gz


# /usr/bin/time -v /home/chf4012/camp_short-read-quality-control/configs/tadpole/bbmap/tadpole.sh mode=correct  t=16 in=AdapterRemoval_306557045_S155_L003_RX_001.pair1.truncated.fastq in2=AdapterRemoval_306557045_S155_L003_RX_001.pair2.truncated.fastq out=/athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/seq_error_306557045_S155_L003_R1_001.fastq.gz out2=/athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/seq_error_306557045_S155_L003_R2_001.fastq.gz


# So that FastQs generated in the previous step will not get deleted
# note that if it's tadpole then no need to be deleted
rule move_corr_reads: 
    input:
        fwd = join(dirs.OUT, '3_error_removal', '{sample}', 'corrected', '{sample}_1.fastq.00.0_0.cor.fastq.gz'),
        rev = join(dirs.OUT, '3_error_removal', '{sample}', 'corrected', '{sample}_2.fastq.00.0_0.cor.fastq.gz'),
    output:
        fwd = join(dirs.OUT, '3_error_removal', '{sample}_1.fastq.gz'),
        rev = join(dirs.OUT, '3_error_removal', '{sample}_2.fastq.gz'),
    params:
        inp_unp = join(dirs.OUT, '3_error_removal', '{sample}', 'corrected', '{sample}__unpaired.00.0_0.cor.fastq.gz'),
        out_unp = join(dirs.OUT, '3_error_removal', '{sample}_unp.fastq.gz'),
    shell:
        """      
        mv {input.fwd} {output.fwd}
        mv {input.rev} {output.rev}
        if [ -f {params.inp_unp} ]; then
            mv {params.inp_unp} {params.out_unp}
        fi
        """


rule fastqc_pre:
    input:
        join(dirs.TMP,'{sample}_{dir}.fastq.gz'),
    output:
        join(dirs.OUT, '4_summary', 'fastqc_pre', '{sample}_{dir}_fastqc.html'),
    conda:
        join(config['env_yamls'], 'multiqc.yaml'),
    params:
        out_dir = join(dirs.OUT, '4_summary', 'fastqc_pre'),
    # run:
    #     if config['qc_option']:
    #         shell("fastqc {input} -d {params.out_dir} --outdir {params.out_dir}")
    #     else:
    #         shell("touch {output}")
    shell:
        """
        fastqc {input} -d {params.out_dir} --outdir {params.out_dir}
        """

# /usr/bin/time -v fastqc 306557045_S155_L003_R1_001.fastq.gz -d /athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/fastqc_pre --outdir /athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/fastqc_pre
rule fastqc_post:
    input:
        join(dirs.OUT, '3_error_removal', '{sample}_{dir}.fastq.gz'),
    output:
        join(dirs.OUT, '4_summary', 'fastqc_post', '{sample}_{dir}_fastqc.html'),
    conda:
        join(config['env_yamls'], 'multiqc.yaml'),
    params:
        out_dir = join(dirs.OUT, '4_summary', 'fastqc_post'),
    shell:
    # run:
    #     if config['qc_option']:
    #         shell("fastqc {input} -d {params.out_dir} --outdir {params.out_dir}")
    #     else:
    #         shell("touch {output}")
        """
        fastqc {input} -d {params.out_dir} --outdir {params.out_dir}
        """

# /usr/bin/time -v fastqc /athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/seq_error_306557045_S155_L003_R1_001.fastq.gz -d /athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/fastqc_post --outdir /athena/masonlab/scratch/users/chf4012/fairbanks/test_big_small/fastqc_post
rule multiqc:
    input:
        lambda wildcards: expand(join(dirs.OUT, '4_summary', 'fastqc_{eval}', '{sample}_{dir}_fastqc.html'), eval = wildcards.eval, sample = SAMPLES, dir = ['1', '2']),
    output:
        join(dirs.OUT, '4_summary', '{eval}_multiqc_report.html'),
    conda:
        join(config['env_yamls'], 'multiqc.yaml'),
    params:
        in_dir = join(dirs.OUT, '4_summary', 'fastqc_{eval}'),
    shell:
    # run:
    #     if config['qc_option']:
    #         shell("multiqc --force {params.in_dir} -n {output}")
    #     else:
    #         shell("touch {output}")
        """
        multiqc --force {params.in_dir} -n {output}
        """


rule init_statistics:
    input:
        fwd = join(dirs.TMP,'{sample}_1.fastq.gz'),
        rev = join(dirs.TMP,'{sample}_2.fastq.gz'),
    output:
        join(dirs.OUT, '{sample}' + '_read_stats.csv'),
    resources:
        mem_mb = config['count_reads_mem_mb'],
    params:
        sample = '{sample}',
    run:
        calc_read_lens(str(params.sample), '0_begin', input, str(output))


rule step_statistics:
    input:
        lambda wildcards: expand(join(dirs.OUT, '{step}', '{sample}_{dir}.fastq.gz'), step = wildcards.step, sample = wildcards.sample, dir = ['1', '2'])
    output:
        join(dirs.OUT, '{step}', '{sample}_read_stats.csv'),
    resources:
        mem_mb = config['count_reads_mem_mb'],
    params:
        sample = '{sample}',
        step = '{step}',
    run:
        calc_read_lens(str(params.sample), str(params.step), input, str(output))

if config['use_host_filter']:
    sample_statistics_steps = ['0_lowqual_removal', '1_adapter_removal', '2_host_removal', '3_error_removal']
else:
    sample_statistics_steps = ['0_lowqual_removal', '1_adapter_removal', '3_error_removal']

rule sample_statistics:
    input:
        init = join(dirs.OUT, '{sample}' + '_read_stats.csv'),
        step = lambda wildcards: expand(join(dirs.OUT, '{step}', '{sample}_read_stats.csv'), step = sample_statistics_steps, sample = wildcards.sample),
    output:
        join(dirs.OUT, '4_summary', '{sample}_read_stats.csv'),
    run:
        sample_statistics([str(input.init)] + input.step, str(output))


rule concat_statistics:
    input:
        expand(join(dirs.OUT, '4_summary', '{sample}_read_stats.csv'), sample = SAMPLES),
    output:
        join(dirs.OUT, 'final_reports', 'read_stats.csv'),
    shell:
        """
        echo -e "sample_name,step,num_reads,prop_init_reads,total_size,prop_init_size,mean_read_len" | cat - {input} > {output}
        """



rule make_config:
    input:
        sts = join(dirs.OUT, 'final_reports', 'read_stats.csv'),
    output:
        cfg = join(dirs.OUT, 'final_reports', 'samples.csv'),
    params: 
        mqc = expand(join(dirs.OUT, '4_summary', '{eval}_multiqc_report.html'), eval = ['pre', 'post']),
        fastq_dir = join(dirs.OUT, '3_error_removal'),
        multiqc_dir = join(dirs.OUT, '4_summary'),
        samples = SAMPLES,
        pre = join(dirs.OUT, 'final_reports', 'pre_multiqc_report.html'),
        post = join(dirs.OUT, 'final_reports', 'post_multiqc_report.html'),
    run:
        if config['qc_option']:
            shutil.copy(str(params.mqc[0]), str(params.pre))
            shutil.copy(str(params.mqc[1]), str(params.post))
        dct = {}
        for i in params.samples:
            s = i.split('/')[-1]
            if s not in dct: dct[s] = {}
            dct[s]['illumina_fwd'] = join(params.fastq_dir, s + '_1.fastq.gz')
            dct[s]['illumina_rev'] = join(params.fastq_dir, s + '_2.fastq.gz')
        df = pd.DataFrame.from_dict(dct, orient ='index')
        df.reset_index(inplace = True)
        df.rename(columns = {'index': 'sample_name'}, inplace = True)
        df.to_csv(str(output.cfg), index = False)
